import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex space-x-4">
            <Link href="/" className="text-white hover:text-gray-300">
              首頁
            </Link>
            <Link href="/week1" className="text-white hover:text-gray-300">
              Week 1
            </Link>
            <Link href="/week2" className="text-white hover:text-gray-300">
              Week 2
            </Link>
            <Link href="/week3" className="text-white hover:text-gray-300">
              Week 3
            </Link>
            <Link href="/week4" className="text-white hover:text-gray-300">
              Week 4
            </Link>
            <Link href="/week5" className="text-white hover:text-gray-300">
              Week 5
            </Link>
            <Link href="/week6" className="text-white hover:text-gray-300">
              Week 6
            </Link>
          </div>
        </nav>
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
